/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlaceTicketSelectionDto } from './placeTicketSelectionDto';


export interface PlaceTicketCommand { 
    playerId?: string;
    stake?: number;
    selections?: Array<PlaceTicketSelectionDto> | null;
}

