/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TicketSelectionLineDto } from './ticketSelectionLineDto';


export interface TicketDetailDto { 
    ticketId?: string;
    createdAtUtc?: string;
    stakeGross?: number;
    stakeNet?: number;
    combinedOdds?: number;
    potentialPayout?: number;
    status?: string | null;
    selections?: Array<TicketSelectionLineDto> | null;
}

