/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TicketPlacedDto { 
    ticketId?: string;
    stakeGross?: number;
    feeAmount?: number;
    stakeNet?: number;
    combinedOdds?: number;
    potentialPayout?: number;
    selectionCount?: number;
    balanceAfter?: number;
}

