/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferCategory } from './offerCategory';


export interface TicketSelectionLineDto { 
    homeTeam?: string | null;
    awayTeam?: string | null;
    outcomeCode?: string | null;
    oddAtPlacement?: number;
    categoryAtPlacement?: OfferCategory;
}



