/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum WalletTransactionType {

    Deposit = 'Deposit',

    BetStakeDebit = 'BetStakeDebit',

    BetFeeDebit = 'BetFeeDebit',

    BetPayoutCredit = 'BetPayoutCredit',

    Refund = 'Refund'
}

