/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WalletTransactionType } from './walletTransactionType';


export interface WalletTransactionDto { 
    occurredAtUtc?: string;
    type?: WalletTransactionType;
    amount?: number;
    referenceId?: string | null;
}



