/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WalletTransactionDto } from './walletTransactionDto';


export interface WalletDto { 
    playerId?: string;
    balance?: number;
    lastTransactions?: Array<WalletTransactionDto> | null;
}

