/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MatchOfferDto } from '../model/models';
import { OfferDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface OffersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param asOfUtc 
     */
    apiOffersActiveGet(asOfUtc?: string, extraHttpRequestParams?: any): Observable<Array<OfferDto>>;

    /**
     * 
     * 
     * @param asOfUtc 
     */
    apiOffersActiveGroupedGet(asOfUtc?: string, extraHttpRequestParams?: any): Observable<Array<MatchOfferDto>>;

}
