/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreatePlayerCommand } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PlayersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createPlayerCommand 
     */
    apiPlayersPost(createPlayerCommand?: CreatePlayerCommand, extraHttpRequestParams?: any): Observable<string>;

}
