/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PlaceTicketCommand } from '../model/models';
import { TicketDetailDto } from '../model/models';
import { TicketPlacedDto } from '../model/models';
import { TicketSummaryDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TicketsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param playerId 
     */
    apiTicketsPlayerPlayerIdGet(playerId: string, extraHttpRequestParams?: any): Observable<Array<TicketSummaryDto>>;

    /**
     * 
     * 
     * @param placeTicketCommand 
     */
    apiTicketsPost(placeTicketCommand?: PlaceTicketCommand, extraHttpRequestParams?: any): Observable<TicketPlacedDto>;

    /**
     * 
     * 
     * @param ticketId 
     */
    apiTicketsTicketIdGet(ticketId: string, extraHttpRequestParams?: any): Observable<TicketDetailDto>;

}
