/**
 * BettingPlatform.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DepositCommand } from '../model/models';
import { WalletDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface WalletServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param depositCommand 
     */
    apiWalletDepositPost(depositCommand?: DepositCommand, extraHttpRequestParams?: any): Observable<WalletDto>;

    /**
     * 
     * 
     * @param playerId 
     */
    apiWalletPlayerIdGet(playerId: string, extraHttpRequestParams?: any): Observable<WalletDto>;

}
